import { StyleSheet, Platform, StatusBar } from 'react-native';
import { theme } from '../../constants/theme';

export const infoPanelStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background.default,
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  header: {
    backgroundColor: theme.colors.header.background,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: Platform.OS === 'android' ? 10 : 40,
    paddingBottom: theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.header.border,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLeft: {
    flex: 1,
  },
  marketName: {
    color: theme.colors.header.text,
    fontSize: theme.typography.fontSizes['3xl'],
    fontWeight: theme.typography.fontWeights.semibold,
    letterSpacing: 0.5,
    marginBottom: theme.spacing.xs,
  },
  date: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: theme.typography.fontSizes.sm,
    fontWeight: theme.typography.fontWeights.normal,
    letterSpacing: 0.3,
  },
  headerButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.md,
  },
  iconButton: {
    padding: theme.spacing.sm,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: theme.borderRadius.sm,
  },
  content: {
    flex: 1,
    backgroundColor: theme.colors.background.dark,
  },
  tableContainer: {
    padding: theme.spacing.lg,
  },
  tableRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: theme.colors.background.paper,
    padding: theme.spacing.lg,
    borderRadius: theme.borderRadius.lg,
    marginBottom: theme.spacing.md,
    borderWidth: 1,
    borderColor: theme.colors.border.main,
  },
  tableLabel: {
    fontSize: theme.typography.fontSizes.lg,
    color: theme.colors.text.primary,
    fontWeight: theme.typography.fontWeights.medium,
    flex: 1,
  },
  tableInput: {
    width: 120,
    height: 40,
    backgroundColor: theme.colors.background.dark,
    borderWidth: 1,
    borderColor: theme.colors.border.main,
    borderRadius: theme.borderRadius.md,
    paddingHorizontal: theme.spacing.md,
    fontSize: theme.typography.fontSizes.lg,
    color: theme.colors.text.primary,
    textAlign: 'right',
  },
  tableValue: {
    fontSize: theme.typography.fontSizes.lg,
    color: theme.colors.text.primary,
    fontWeight: theme.typography.fontWeights.semibold,
    backgroundColor: theme.colors.background.dark,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.borderRadius.md,
    overflow: 'hidden',
    width: 120,
    textAlign: 'right',
  },
  footer: {
    backgroundColor: theme.colors.background.paper,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border.main,
    padding: theme.spacing.lg,
    paddingBottom: Platform.OS === 'ios' ? 24 : theme.spacing.lg,
  },
  remainderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: theme.colors.background.dark,
    padding: theme.spacing.lg,
    borderRadius: theme.borderRadius.lg,
    marginBottom: theme.spacing.lg,
    borderWidth: 1,
    borderColor: theme.colors.border.main,
  },
  remainderLabel: {
    fontSize: theme.typography.fontSizes.xl,
    color: theme.colors.text.primary,
    fontWeight: theme.typography.fontWeights.semibold,
  },
  remainderValue: {
    fontSize: theme.typography.fontSizes['2xl'],
    color: theme.colors.primary.main,
    fontWeight: theme.typography.fontWeights.bold,
    backgroundColor: theme.colors.primary.background,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.borderRadius.md,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.colors.primary.light,
    minWidth: 120,
    textAlign: 'right',
  },
  confirmButtonContainer: {
    borderRadius: theme.borderRadius.lg,
    overflow: 'hidden',
  },
  confirmButton: {
    backgroundColor: theme.colors.primary.main,
    paddingVertical: theme.spacing.md,
  },
  confirmButtonText: {
    fontSize: theme.typography.fontSizes.lg,
    fontWeight: theme.typography.fontWeights.semibold,
  },
}); 